### ISSUE TITLE
code needs documentation

### ISSUE THREAD

**Issue by Algo-ryth-mix** [Args-Engine/Args-Engine#16]
For the code to be automatically documented it needs to be well documented.(duh, I know)
Some files in the repository do currently not follow the common doxygen guidelines.

https://www.doxygen.nl/manual/starting.html

**Comment by GlynLeine** [comment]
correct, the first few lines of code that were published is mostly placeholder, hence no documentation. the UML needs to be worked out to a certain degree first before i can continue putting code down. documentation will come at that stage as well.

**Comment by Algo-ryth-mix** [comment]
fair point, I mostly ported finished code into args which was tbf already documented. I will go over the files later to find anything that can be documented by me or the author(s)
