### ISSUE TITLE
primitives.hpp and types.hpp ambiguity

### ISSUE THREAD

**Issue by Algo-ryth-mix** [Args-Engine/Args-Engine#17]
Unless there is some good reason to keep them seperate I advise on joining these two

For which one please discuss in the comments or via discord

**Comment by GlynLeine** [comment]
primitives is more specific and might better describe what the header is needed for, however types.hpp would allow for more flexibility but possibly also ambiguity. technically meta.hpp also keeps types, and so does almost every other header.

**Comment by Algo-ryth-mix** [comment]
what about
types/types.hpp which is empty except for
```cpp
	#include <core/types/primitives.hpp>
	#include <core/types/meta.hpp>
	//... other includes that might come up in the future
```

**Comment by GlynLeine** [comment]
yes that seems like a fine solution, a single include header for all utility types and type defs
