### ISSUE TITLE
Entity Query does not contain the requested components

### ISSUE THREAD

**Issue by Developer-The-Great** [Args-Engine/Args-Engine#231]
**Describe the bug**
Entity Query does not contain the requested components even after instantiating an entity that has the required components

**Include a MRE**
1. create a query
![image](https://user-images.githubusercontent.com/37859544/101370851-4f3e2280-38aa-11eb-9f12-f6f54523bec4.png)
2. initialize an entity has the required components for the query
![image](https://user-images.githubusercontent.com/37859544/101371369-f622be80-38aa-11eb-9dad-6828e241e54d.png)

3. attempt to iterate through the query/log its size
![image](https://user-images.githubusercontent.com/37859544/101371022-92989100-38aa-11eb-90d0-6a6c6fb5d832.png)

4. The query is empty
![image](https://user-images.githubusercontent.com/37859544/101371813-79dcab00-38ab-11eb-8505-36f6c7ce43d2.png)

**Expected behavior**
After adding an entity that has the requested queries, it should appear in the query.

**Comment by Algo-ryth-mix** [comment]
queries do now require you to manually query:
call `queryEntities()` on the Query
