### ISSUE TITLE
PP Pipeline Improvements

### ISSUE THREAD

**Issue by kukash** [Args-Engine/Args-Engine#251]
**Render Pass function**
Render pass function should not always give pass color texture and depth texture. The user should be able to decide what input he wants. We probably want to acces stuff like depth texture, normal buffer etc  within the shader, as a part of the shader library.

**Shader Library**
As mentioned in the issue above we want to make use of the shader library within post processing effects. We also want to add functionalities like depthTexture to the library.

**Effect exectuion order**
Priority is ambiguous (for me at least), is a low number low prio, or high prio?
I would change up the name or the variable to make that more clear or change the way effect execution order is handled.

**Comment by GlynLeine** [comment]
Most of these are already fixed; However as of now with the current postprocessing stage I'm not going to fix this since I'm first busy with a rebuild of Core. after that the entire renderer will get another look over again as well so the way post processing effects work might change entirely.
