### ISSUE TITLE
core/common/common.hpp: assert_msg  should probably be part of args::core::logging in core/logging/*

### ISSUE THREAD

**Issue by GlynLeine** [Args-Engine/Args-Engine#37]
debug tools like assertions and logging should probably be part of the core::logging part of the engine. this was later on when we build editor consoles we can also log asserts to the editor.

**Comment by Algo-ryth-mix** [comment]
cassert is a more or less destructive operation, a failing assertion will quit the program, I am not sure this falls into the category of "editor-tool" not an editor tool I would want to use anyways

**Comment by GlynLeine** [comment]
if you see how unreal and unity handle errors, they catch everything and log the error to prevent the editor from crashing. this way the internal application can crash and exit play mode whilst the editor keeps running.

**Comment by Algo-ryth-mix** [comment]
Exactly, but assert_msg is not this operation, <cassert> only works in debug mode and failure signifies an unrecoverable error

**Comment by GlynLeine** [comment]
so if this happens everything should crash? even the outside editor that's just hosting it?
it's either that or we need the editor to run the game inside a seperate process or a vm when in the editor.

**Comment by Algo-ryth-mix** [comment]
> so if this happens everything should crash? even the outside editor that's just hosting it?

that is how \<cassert\> works yes. For something else we need a different solution. `assert_msg` is just a wrapper around `assert`so that instead of 
_Assertion failed: expression, file_ filename, _line_ line-number
_Assertion failed: **(msg, expression)** , file_ filename, _line_ line-number
is printed

## From the standard:
`void assert (int expression);`

### Evaluate assertion
If the argument expression of this macro with functional form compares equal to zero (i.e., the expression is false), a message is written to the standard error device and [abort](http://www.cplusplus.com/reference/cstdlib/abort/) is called, terminating the program execution.

**Comment by GlynLeine** [comment]
yeah after some extra thinking whilst i was driving today i also came to the conclusion that the playing in the editor needs to be a seperate process anyways. not just because of security and stability reasons but also because of the constraints of C++. if we are to have C++ as a scripting language as well the C++ code will have to be recompiled after a script change. Adding or removing engine modules will also need a recompile. recompiling the game without restarting the editor means that the play mode game needs to be a seperate process managed and hosted by the editor.

besides that it's probably still a better idea to keep the macro's and functions for assertion near the ones for logging? just so you could easily include both from a single header if need be.

**Comment by Algo-ryth-mix** [comment]
I don't know if we actually want a user to use cassert, I see no inherent problem with moving assert_msg to a logging header other than it not really making sense. I could however see how it might be included when including <core/debugging.h> or something similar together with the contents of a potential logging system

**Comment by GlynLeine** [comment]
yes the debugging.h was indeed what i had in mind, maybe logging needs to be renamed to debugtools or something of the likes.
but even if the user doesn't use cassert, parts of the engine does. things might still be able to go wrong from code triggered by the user through the API.

**Comment by Algo-ryth-mix** [comment]
yes... that is what you call a bug
while things can go wrong with the users code, the user should not be able to do something that crashes the engine

**Comment by Algo-ryth-mix** [comment]
but when things go wrong we want an assert to be in place to at least be able to tell what went wrong

**Comment by GlynLeine** [comment]
> yes... that is what you call a bug
> while things can go wrong with the users code, the user should not be able to do something that crashes the engine

should not be able to yes, but it might still happen. no code is ever fully bug free. we need to be prepared in the case it does happen. preferably with a game crash without the editor crashing and an automatic bug report form pop up.

**Comment by Algo-ryth-mix** [comment]
the idea of assert is to report an unrecoverable error and quit the application. The current use for it is in the low-level file api in the case that you attempt to access a file that does not exist. read_file and write_file has no mechanism to report errors and also should not need to. and this is exactly the use for assert, you **require** that something is checked beforehand and crash when your assumptions are not met. it is not a tool and end-user of the engine should use. simmilarly assert should not be used in code that is interactible with the user, read_file and write_file while technically accessible are meant to be hidden behind the virtual filesystem adapter code. 

assert_msg is just a dumb wrapper around assert it's only purpose is to include a message with the assertion failure, it should not be exposed to users, it should not be used for error-reporting, but only for assumption checking.

**Comment by GlynLeine** [comment]
okay, but then it should maybe still fall under debug instead of common?

**Comment by Algo-ryth-mix** [comment]
I would probably put it in /detail/debug such that it is clear that it is an implementation detail of the engine

**Comment by GlynLeine** [comment]
makes sense, that'll be a dir that needs to be made then
