### ISSUE TITLE
We need a license

### ISSUE THREAD

**Issue by GlynLeine** [Args-Engine/Args-Engine#51]

**Comment by Algo-ryth-mix** [comment]
There is a few options here:
- MIT
- BSD
- Apache
- Maybe LGPL
- Boost

Each have their up and downsides

In my opinion stuff like the GPL disqualify themselves for being viral (e.g.: code developed based on GPL stuff also needs to be GPL)

CC0 AND WTFPL, are a bit much in terms of openness going as far as not crediting the original work at all.

Submodules that are ported from lpe-legacy are MIT in nature, which should be compatible with everything besides WTFPL and CC0.

I would not recommend custom licenses

**Comment by Algo-ryth-mix** [comment]
https://choosealicense.com/

**Comment by Algo-ryth-mix** [comment]
Based on what we want to do I would recommend either MIT or ISC, with ISC being basically a modernized MIT

**Comment by GlynLeine** [comment]
would MIT and ISC block any of us from monetizing the engine in the future?

**Comment by Algo-ryth-mix** [comment]
Most likely, but for monetization, you will  most probably require a laywer

**Comment by Algo-ryth-mix** [comment]
It does not prohibit from creating products based on args-engine that are monetized

**Comment by GlynLeine** [comment]
hmmmm..... so you could build a monetized engine that's highly inspired by this engine?

**Comment by Algo-ryth-mix** [comment]
Yes, as long as you credit the original authors

**Comment by GlynLeine** [comment]
cool cool, ISC it is then!

**Comment by GlynLeine** [comment]
wait MIT is more integrated with GIT, and they're functionally the same right?
