### ISSUE TITLE
Reliance of instable compiler feature: inline static variables

### ISSUE THREAD

**Issue by GlynLeine** [Args-Engine/Args-Engine#95]
**Describe the bug**
Inline static variables have a very unstable and hard to predict behaviour when headers with them get included in multiple different .cpp files. they should be avoided for now and an alternative solution should be found.

**Include a MRE**
baz.hpp:

    struct baz
    {
        static inline int var;
        static void foo();
    };

baz.cpp:

    #include <iostream>
    #include "baz.hpp"

    void baz::foo()
    {
        var = 1;
        std::cout << var << std::endl;
    }

bar.hpp:

    struct bar
    {
        static void foo();
    };

bar.cpp:

    #include <iostream>
    #include "baz.hpp"
    #include "bar.hpp"

    void bar::foo()
    {
        std::cout << baz::var << std::endl;
    }
main.cpp:

    #include <iostream>
    #include "baz.hpp"

    int main()
    {
        baz::foo();
        bar::foo();
        return 0;
    }

will output:

    1
    0

**Screenshots**
printing out the size of AssetImporter::m_converters in multiple places throughout the engine:
![](https://media.discordapp.net/attachments/682321169541890070/749743925060698152/unknown.png)

**Comment by Algo-ryth-mix** [comment]
Edited `inline` to `inline static` as they mean very different things
